#pragma once

extern "C" int deep_ep_ascend_launch_direct_dispatch_acquire_route_plan(
    std::uint8_t* workspace,
    std::int32_t* prefix_per_rank,
    std::int32_t* prefix_per_expert,
    std::int32_t* unaligned_per_expert,
    std::uint32_t transport_abi_version,
    std::uint32_t transport_struct_size,
    std::uint64_t transport_capabilities,
    std::uintptr_t transport_local_window_base,
    std::uintptr_t transport_channel_table,
    std::uintptr_t transport_peer_address_table,
    std::uint32_t transport_topology_abi_version,
    std::uint32_t transport_topology_struct_size,
    int transport_world_rank,
    int transport_world_size,
    int transport_scale_up_rank,
    int transport_scale_up_size,
    int transport_scale_out_rank,
    int transport_scale_out_size,
    std::uint32_t transport_scale_up_direct,
    std::uint32_t transport_topology_kind,
    std::uint64_t transport_topology_epoch,
    std::uintptr_t transport_backend_context,
    std::uint64_t generation,
    std::uint64_t timeout_cycles,
    std::uint64_t num_experts,
    std::uint64_t expert_alignment,
    std::uint64_t shard_capacity,
    std::uint64_t dispatch_output_capacity,
    std::uint64_t dispatch_route_plan_offset,
    std::uint64_t dispatch_route_plan_slot_bytes,
    std::uint64_t dispatch_route_plan_expert_capacity,
    std::uint64_t workspace_status_offset,
    std::uint64_t workspace_route_source_counts_offset,
    std::uint64_t workspace_rank_values_offset,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_epilogue_acquire(
    std::uint8_t* communication_buffer,
    std::uint8_t* workspace,
    const std::int32_t* prefix_per_rank,
    std::uint32_t transport_abi_version,
    std::uint32_t transport_struct_size,
    std::uint64_t transport_capabilities,
    std::uintptr_t transport_local_window_base,
    std::uintptr_t transport_channel_table,
    std::uintptr_t transport_peer_address_table,
    std::uint32_t transport_topology_abi_version,
    std::uint32_t transport_topology_struct_size,
    int transport_world_rank,
    int transport_world_size,
    int transport_scale_up_rank,
    int transport_scale_up_size,
    int transport_scale_out_rank,
    int transport_scale_out_size,
    std::uint32_t transport_scale_up_direct,
    std::uint32_t transport_topology_kind,
    std::uint64_t transport_topology_epoch,
    std::uintptr_t transport_backend_context,
    CoreModeFlags mode_flags,
    std::uint64_t generation,
    std::uint64_t timeout_cycles,
    std::uint64_t num_experts,
    std::uint64_t expert_alignment,
    std::uint64_t shard_capacity,
    std::uint64_t dispatch_output_capacity,
    std::uint64_t dispatch_control_offset,
    std::uint64_t dispatch_control_bytes,
    std::uint64_t dispatch_receive_shard_bytes,
    std::uint64_t dispatch_receive_shard_count,
    std::uint64_t dispatch_receive_bytes,
    std::uint64_t workspace_status_offset,
    std::uint64_t workspace_local_count_offset,
    std::uint64_t workspace_rank_counts_offset,
    std::uint64_t workspace_route_source_counts_offset,
    std::uint64_t workspace_rank_values_offset,
    std::uint64_t workspace_rank_count,
    std::uint64_t dispatch_error_offset,
    std::uint64_t dispatch_error_count,
    std::uint64_t dispatch_rank_bitmap_bytes,
    std::uint64_t dispatch_expert_bitmap_bytes,
    std::uint64_t dispatch_pipeline_offset,
    std::uint64_t dispatch_pipeline_bytes,
    std::uint64_t token_stride_bytes,
    std::uint32_t early_route_plan,
    std::uint32_t persistent_source_pipeline,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_epilogue_assign_destinations(
    std::uint8_t* communication_buffer,
    std::uint8_t* workspace,
    const std::int32_t* prefix_per_expert,
    const std::int32_t* unaligned_per_expert,
    std::int32_t* source_metadata,
    std::uintptr_t transport_local_window_base,
    int transport_world_rank,
    int transport_world_size,
    CoreModeFlags mode_flags,
    std::uint64_t generation,
    std::uint64_t num_experts,
    std::uint64_t num_topk,
    std::uint64_t shard_capacity,
    std::uint64_t dispatch_output_capacity,
    std::uint64_t dispatch_receive_offset,
    std::uint64_t dispatch_receive_shard_bytes,
    std::uint64_t workspace_status_offset,
    std::uint64_t workspace_rank_counts_offset,
    std::uint64_t workspace_rank_values_offset,
    std::uint64_t dispatch_expert_tile_count_offset,
    std::uint64_t dispatch_expert_tile_count,
    std::uint64_t dispatch_error_offset,
    std::uint64_t dispatch_expert_bitmap_offset,
    std::uint64_t token_stride_bytes,
    std::uint64_t token_topk_index_offset,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_epilogue_clear_padding(
    std::uint8_t* workspace,
    std::uint8_t* recv_x,
    std::uint8_t* recv_scale_factors,
    float* recv_topk_weights,
    const std::int32_t* prefix_per_expert,
    CoreModeFlags mode_flags,
    std::uint64_t num_experts,
    std::uint64_t token_hidden_bytes,
    std::uint64_t token_scale_factor_bytes,
    std::uint64_t recv_scale_factor_token_stride,
    std::uint64_t recv_scale_factor_pack_stride,
    std::uint64_t workspace_status_offset,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_epilogue_copy_outputs(
    std::uint8_t* communication_buffer,
    std::uint8_t* workspace,
    std::uint8_t* recv_x,
    std::uint8_t* recv_scale_factors,
    float* recv_topk_weights,
    const std::int32_t* source_metadata,
    std::uintptr_t transport_local_window_base,
    int transport_world_size,
    CoreModeFlags mode_flags,
    std::uint64_t num_topk,
    std::uint64_t shard_capacity,
    std::uint64_t dispatch_receive_offset,
    std::uint64_t dispatch_receive_shard_bytes,
    std::uint64_t workspace_status_offset,
    std::uint64_t workspace_rank_counts_offset,
    std::uint64_t workspace_rank_values_offset,
    std::uint64_t token_stride_bytes,
    std::uint64_t token_hidden_offset,
    std::uint64_t token_hidden_bytes,
    std::uint64_t hidden_copy_begin,
    std::uint64_t token_scale_factor_offset,
    std::uint64_t token_scale_factor_bytes,
    std::uint64_t recv_scale_factor_token_stride,
    std::uint64_t recv_scale_factor_pack_stride,
    std::uint64_t token_topk_index_offset,
    std::uint64_t token_topk_weight_offset,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_epilogue_count_experts(
    std::uint8_t* communication_buffer,
    std::uint8_t* workspace,
    std::uintptr_t transport_local_window_base,
    int transport_world_rank,
    int transport_world_size,
    std::uint64_t num_experts,
    std::uint64_t num_topk,
    std::uint64_t shard_capacity,
    std::uint64_t dispatch_receive_offset,
    std::uint64_t dispatch_receive_shard_bytes,
    std::uint64_t workspace_status_offset,
    std::uint64_t workspace_rank_counts_offset,
    std::uint64_t dispatch_expert_tile_count_offset,
    std::uint64_t dispatch_expert_tile_count,
    std::uint64_t token_stride_bytes,
    std::uint64_t token_topk_index_offset,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_epilogue_metadata(
    std::uint8_t* communication_buffer,
    std::uint8_t* workspace,
    std::int64_t* recv_topk_indices,
    std::int32_t* source_metadata,
    std::uintptr_t transport_local_window_base,
    int transport_world_rank,
    int transport_world_size,
    CoreModeFlags mode_flags,
    std::uint64_t num_experts,
    std::uint64_t num_topk,
    std::uint64_t shard_capacity,
    std::uint64_t dispatch_receive_offset,
    std::uint64_t dispatch_receive_shard_bytes,
    std::uint64_t workspace_status_offset,
    std::uint64_t workspace_rank_counts_offset,
    std::uint64_t workspace_rank_values_offset,
    std::uint64_t token_stride_bytes,
    std::uint64_t token_topk_index_offset,
    std::uint64_t token_source_metadata_offset,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_epilogue_parallel_prefix(
    std::uint8_t* workspace,
    std::int32_t* prefix_per_rank,
    std::int32_t* prefix_per_expert,
    std::int32_t* unaligned_per_expert,
    std::uint32_t transport_abi_version,
    std::uint32_t transport_struct_size,
    std::uint64_t transport_capabilities,
    std::uintptr_t transport_local_window_base,
    std::uintptr_t transport_channel_table,
    std::uintptr_t transport_peer_address_table,
    std::uint32_t transport_topology_abi_version,
    std::uint32_t transport_topology_struct_size,
    int transport_world_rank,
    int transport_world_size,
    int transport_scale_up_rank,
    int transport_scale_up_size,
    int transport_scale_out_rank,
    int transport_scale_out_size,
    std::uint32_t transport_scale_up_direct,
    std::uint32_t transport_topology_kind,
    std::uint64_t transport_topology_epoch,
    std::uintptr_t transport_backend_context,
    std::uint64_t generation,
    std::uint64_t num_experts,
    std::uint64_t expert_alignment,
    std::uint64_t dispatch_output_capacity,
    std::uint64_t workspace_status_offset,
    std::uint64_t workspace_rank_counts_offset,
    std::uint64_t dispatch_expert_tile_count_offset,
    std::uint64_t dispatch_expert_tile_count,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_epilogue_prefix(
    std::uint8_t* workspace,
    std::int32_t* prefix_per_rank,
    std::int32_t* prefix_per_expert,
    std::int32_t* unaligned_per_expert,
    std::uint32_t transport_abi_version,
    std::uint32_t transport_struct_size,
    std::uint64_t transport_capabilities,
    std::uintptr_t transport_local_window_base,
    std::uintptr_t transport_channel_table,
    std::uintptr_t transport_peer_address_table,
    std::uint32_t transport_topology_abi_version,
    std::uint32_t transport_topology_struct_size,
    int transport_world_rank,
    int transport_world_size,
    int transport_scale_up_rank,
    int transport_scale_up_size,
    int transport_scale_out_rank,
    int transport_scale_out_size,
    std::uint32_t transport_scale_up_direct,
    std::uint32_t transport_topology_kind,
    std::uint64_t transport_topology_epoch,
    std::uintptr_t transport_backend_context,
    CoreModeFlags mode_flags,
    std::uint64_t generation,
    std::uint64_t num_experts,
    std::uint64_t expert_alignment,
    std::uint64_t dispatch_output_capacity,
    std::uint64_t workspace_status_offset,
    std::uint64_t workspace_rank_counts_offset,
    std::uint64_t dispatch_expert_tile_count_offset,
    std::uint64_t dispatch_expert_tile_count,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_epilogue_validate_records(
    std::uint8_t* communication_buffer,
    std::uint8_t* workspace,
    const std::int32_t* source_metadata,
    deep_ep::ascend::transport::DeviceTransportContext context,
    CoreModeFlags mode_flags,
    std::uint64_t generation,
    std::uint64_t num_experts,
    std::uint64_t num_topk,
    std::uint64_t shard_capacity,
    std::uint64_t dispatch_receive_offset,
    std::uint64_t dispatch_receive_shard_bytes,
    std::uint64_t workspace_status_offset,
    std::uint64_t workspace_rank_counts_offset,
    std::uint64_t workspace_rank_values_offset,
    std::uint64_t dispatch_receive_tile_error_offset,
    std::uint64_t dispatch_receive_error_candidate_offset,
    std::uint64_t dispatch_receive_error_completion_offset,
    std::uint64_t dispatch_receive_tile_count,
    std::uint64_t token_stride_bytes,
    std::uint64_t token_topk_index_offset,
    std::uint64_t token_source_metadata_offset,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_persistent_chunk_begin(
    std::uint8_t* workspace,
    std::uint64_t dispatch_pipeline_offset,
    std::uint64_t generation,
    std::uint32_t source_chunk_count,
    std::uint32_t source_chunk_tiles,
    std::uint32_t source_chunk,
    std::uint32_t source_tile_begin,
    std::uint32_t source_tile_end,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_persistent_chunk_complete(
    std::uint8_t* workspace,
    std::uint64_t dispatch_pipeline_offset,
    std::uint32_t source_chunk,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_persistent_producer(
    const std::uint8_t* x,
    const std::uint8_t* scale_factors,
    const std::int64_t* topk_indices,
    const float* topk_weights,
    std::uint8_t* communication_buffer,
    std::uint8_t* workspace,
    std::int32_t* destination_slots,
    std::uintptr_t transport_local_window_base,
    int transport_world_rank,
    int transport_world_size,
    CoreModeFlags mode_flags,
    std::uint32_t use_grouping,
    std::uint64_t num_tokens,
    std::uint64_t num_experts,
    std::uint64_t num_topk,
    std::uint64_t shard_capacity,
    std::uint64_t dispatch_receive_offset,
    std::uint64_t dispatch_receive_shard_bytes,
    std::uint64_t dispatch_staging_offset,
    std::uint64_t dispatch_staging_shard_bytes,
    std::uint64_t workspace_status_offset,
    std::uint64_t dispatch_group_owner_offset,
    std::uint64_t dispatch_group_tile_offset,
    std::uint64_t dispatch_group_tile_count,
    std::uint64_t dispatch_pipeline_offset,
    std::uint64_t token_stride_bytes,
    std::uint64_t token_hidden_offset,
    std::uint64_t token_hidden_bytes,
    std::uint64_t hidden_copy_begin,
    std::uint32_t source_chunk_tiles,
    std::uint32_t source_chunk_count,
    std::uint64_t token_scale_factor_offset,
    std::uint64_t token_scale_factor_bytes,
    std::uint64_t scale_factor_token_stride,
    std::uint64_t scale_factor_pack_stride,
    std::uint64_t token_topk_index_offset,
    std::uint64_t token_topk_weight_offset,
    std::uint64_t token_source_metadata_offset,
    std::uint64_t generation,
    std::uint64_t timeout_cycles,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_persistent_release(
    std::uint8_t* communication_buffer,
    std::uint8_t* workspace,
    std::uint32_t transport_abi_version,
    std::uint32_t transport_struct_size,
    std::uint64_t transport_capabilities,
    std::uintptr_t transport_local_window_base,
    std::uintptr_t transport_channel_table,
    std::uintptr_t transport_peer_address_table,
    std::uint32_t transport_topology_abi_version,
    std::uint32_t transport_topology_struct_size,
    int transport_world_rank,
    int transport_world_size,
    int transport_scale_up_rank,
    int transport_scale_up_size,
    int transport_scale_out_rank,
    int transport_scale_out_size,
    std::uint32_t transport_scale_up_direct,
    std::uint32_t transport_topology_kind,
    std::uint64_t transport_topology_epoch,
    std::uintptr_t transport_backend_context,
    std::uint64_t generation,
    std::uint64_t timeout_cycles,
    std::uint64_t dispatch_control_offset,
    std::uint64_t dispatch_receive_offset,
    std::uint64_t dispatch_receive_shard_bytes,
    std::uint64_t dispatch_staging_offset,
    std::uint64_t dispatch_staging_shard_bytes,
    std::uint64_t workspace_status_offset,
    std::uint64_t workspace_local_count_offset,
    std::uint64_t workspace_rank_counts_offset,
    std::uint64_t dispatch_pipeline_offset,
    std::uint64_t dispatch_pipeline_bytes,
    std::uint64_t dispatch_group_tile_offset,
    std::uint64_t dispatch_group_tile_count,
    std::uint32_t release_chunk_tiles,
    std::uint32_t release_chunk_count,
    std::uint32_t producer_blocks,
    std::uint64_t token_stride_bytes,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_persistent_release_complete(
    std::uint8_t* workspace,
    std::uint64_t dispatch_pipeline_offset,
    std::uint64_t generation,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_persistent_release_tail_wait(
    std::uint8_t* workspace,
    std::uint64_t dispatch_pipeline_offset,
    std::uint64_t generation,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_persistent_release_wait(
    std::uint8_t* workspace,
    std::uint64_t dispatch_pipeline_offset,
    std::uint64_t generation,
    std::uint32_t source_chunk,
    std::uint32_t producer_blocks,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_pipeline_wait(
    std::uint8_t* workspace,
    std::uint32_t transport_abi_version,
    std::uint32_t transport_struct_size,
    std::uint64_t transport_capabilities,
    std::uintptr_t transport_local_window_base,
    std::uintptr_t transport_channel_table,
    std::uintptr_t transport_peer_address_table,
    std::uint32_t transport_topology_abi_version,
    std::uint32_t transport_topology_struct_size,
    int transport_world_rank,
    int transport_world_size,
    int transport_scale_up_rank,
    int transport_scale_up_size,
    int transport_scale_out_rank,
    int transport_scale_out_size,
    std::uint32_t transport_scale_up_direct,
    std::uint32_t transport_topology_kind,
    std::uint64_t transport_topology_epoch,
    std::uintptr_t transport_backend_context,
    std::uint64_t dispatch_pipeline_offset,
    std::uint32_t pipeline_chunk_index,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_producer_control(
    std::uint8_t* workspace,
    std::uint32_t transport_abi_version,
    std::uint32_t transport_struct_size,
    std::uint64_t transport_capabilities,
    std::uintptr_t transport_local_window_base,
    std::uintptr_t transport_channel_table,
    std::uintptr_t transport_peer_address_table,
    std::uint32_t transport_topology_abi_version,
    std::uint32_t transport_topology_struct_size,
    int transport_world_rank,
    int transport_world_size,
    int transport_scale_up_rank,
    int transport_scale_up_size,
    int transport_scale_out_rank,
    int transport_scale_out_size,
    std::uint32_t transport_scale_up_direct,
    std::uint32_t transport_topology_kind,
    std::uint64_t transport_topology_epoch,
    std::uintptr_t transport_backend_context,
    std::uint64_t generation,
    std::uint64_t num_experts,
    std::uint64_t shard_capacity,
    std::uint64_t dispatch_output_capacity,
    std::uint64_t dispatch_control_bytes,
    std::uint64_t dispatch_receive_shard_bytes,
    std::uint64_t dispatch_receive_shard_count,
    std::uint64_t dispatch_receive_bytes,
    std::uint64_t dispatch_staging_shard_bytes,
    std::uint64_t dispatch_staging_shard_count,
    std::uint64_t dispatch_staging_bytes,
    std::uint64_t workspace_status_offset,
    std::uint64_t workspace_local_count_offset,
    std::uint64_t workspace_rank_count,
    std::uint64_t dispatch_error_offset,
    std::uint64_t dispatch_error_count,
    std::uint64_t dispatch_rank_bitmap_bytes,
    std::uint64_t dispatch_expert_bitmap_bytes,
    std::uint64_t dispatch_receive_error_candidate_offset,
    std::uint64_t dispatch_receive_error_completion_offset,
    std::uint64_t token_stride_bytes,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_producer_expert_count_init(
    std::uint8_t* workspace,
    std::uint64_t workspace_status_offset,
    std::uint64_t dispatch_group_expert_count_offset,
    std::uint64_t dispatch_group_expert_count,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_producer_plan(
    const std::int64_t* topk_indices,
    std::int32_t* destination_slots,
    std::uint8_t* workspace,
    int transport_world_rank,
    int transport_world_size,
    CoreModeFlags mode_flags,
    std::uint64_t generation,
    std::uint64_t num_tokens,
    std::uint64_t num_experts,
    std::uint64_t num_topk,
    std::uint64_t shard_capacity,
    std::uint64_t workspace_status_offset,
    std::uint64_t workspace_rank_counts_offset,
    std::uint64_t workspace_rank_values_offset,
    std::uint64_t dispatch_error_offset,
    std::uint64_t dispatch_rank_bitmap_offset,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_producer_record(
    const std::uint8_t* x,
    const std::uint8_t* scale_factors,
    const std::int64_t* topk_indices,
    const float* topk_weights,
    std::uint8_t* communication_buffer,
    std::uint8_t* workspace,
    std::int32_t* destination_slots,
    std::uintptr_t transport_local_window_base,
    int transport_world_rank,
    int transport_world_size,
    CoreModeFlags mode_flags,
    std::uint32_t use_grouping,
    std::uint64_t num_tokens,
    std::uint64_t num_experts,
    std::uint64_t num_topk,
    std::uint64_t shard_capacity,
    std::uint64_t dispatch_receive_offset,
    std::uint64_t dispatch_receive_shard_bytes,
    std::uint64_t dispatch_staging_offset,
    std::uint64_t dispatch_staging_shard_bytes,
    std::uint64_t workspace_status_offset,
    std::uint64_t dispatch_group_owner_offset,
    std::uint64_t dispatch_group_tile_offset,
    std::uint64_t dispatch_group_tile_count,
    std::uint64_t token_stride_bytes,
    std::uint64_t token_hidden_offset,
    std::uint64_t token_hidden_bytes,
    std::uint64_t hidden_copy_begin,
    std::uint64_t pipeline_chunk_begin,
    std::uint64_t pipeline_chunk_end,
    std::uint32_t pipeline_source_chunk,
    std::uint64_t token_scale_factor_offset,
    std::uint64_t token_scale_factor_bytes,
    std::uint64_t scale_factor_token_stride,
    std::uint64_t scale_factor_pack_stride,
    std::uint64_t token_topk_index_offset,
    std::uint64_t token_topk_weight_offset,
    std::uint64_t token_source_metadata_offset,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_producer_release(
    std::uint8_t* communication_buffer,
    std::uint8_t* workspace,
    std::uint32_t transport_abi_version,
    std::uint32_t transport_struct_size,
    std::uint64_t transport_capabilities,
    std::uintptr_t transport_local_window_base,
    std::uintptr_t transport_channel_table,
    std::uintptr_t transport_peer_address_table,
    std::uint32_t transport_topology_abi_version,
    std::uint32_t transport_topology_struct_size,
    int transport_world_rank,
    int transport_world_size,
    int transport_scale_up_rank,
    int transport_scale_up_size,
    int transport_scale_out_rank,
    int transport_scale_out_size,
    std::uint32_t transport_scale_up_direct,
    std::uint32_t transport_topology_kind,
    std::uint64_t transport_topology_epoch,
    std::uintptr_t transport_backend_context,
    std::uint64_t generation,
    std::uint64_t timeout_cycles,
    std::uint64_t dispatch_control_offset,
    std::uint64_t dispatch_receive_offset,
    std::uint64_t dispatch_receive_shard_bytes,
    std::uint64_t dispatch_staging_offset,
    std::uint64_t dispatch_staging_shard_bytes,
    std::uint64_t workspace_status_offset,
    std::uint64_t workspace_local_count_offset,
    std::uint64_t workspace_rank_counts_offset,
    std::uint64_t dispatch_pipeline_offset,
    std::uint64_t dispatch_pipeline_bytes,
    std::uint64_t dispatch_group_tile_offset,
    std::uint64_t dispatch_group_tile_count,
    std::uint64_t pipeline_chunk_begin,
    std::uint64_t pipeline_chunk_end,
    std::uint32_t pipeline_chunk_index,
    std::uint32_t pipeline_final_chunk,
    std::uint32_t pipeline_source_chunk,
    std::uint64_t token_stride_bytes,
    std::uint32_t release_segment_value,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_publish_route_plan(
    std::uint8_t* workspace,
    std::uint32_t transport_abi_version,
    std::uint32_t transport_struct_size,
    std::uint64_t transport_capabilities,
    std::uintptr_t transport_local_window_base,
    std::uintptr_t transport_channel_table,
    std::uintptr_t transport_peer_address_table,
    std::uint32_t transport_topology_abi_version,
    std::uint32_t transport_topology_struct_size,
    int transport_world_rank,
    int transport_world_size,
    int transport_scale_up_rank,
    int transport_scale_up_size,
    int transport_scale_out_rank,
    int transport_scale_out_size,
    std::uint32_t transport_scale_up_direct,
    std::uint32_t transport_topology_kind,
    std::uint64_t transport_topology_epoch,
    std::uintptr_t transport_backend_context,
    std::uint64_t generation,
    std::uint64_t timeout_cycles,
    std::uint64_t dispatch_route_plan_offset,
    std::uint64_t dispatch_route_plan_slot_bytes,
    std::uint64_t dispatch_staging_offset,
    std::uint64_t dispatch_staging_shard_bytes,
    std::uint64_t workspace_status_offset,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_reduce_errors(
    std::uint8_t* workspace,
    std::uint32_t transport_abi_version,
    std::uint32_t transport_struct_size,
    std::uint64_t transport_capabilities,
    std::uintptr_t transport_local_window_base,
    std::uintptr_t transport_channel_table,
    std::uintptr_t transport_peer_address_table,
    std::uint32_t transport_topology_abi_version,
    std::uint32_t transport_topology_struct_size,
    int transport_world_rank,
    int transport_world_size,
    int transport_scale_up_rank,
    int transport_scale_up_size,
    int transport_scale_out_rank,
    int transport_scale_out_size,
    std::uint32_t transport_scale_up_direct,
    std::uint32_t transport_topology_kind,
    std::uint64_t transport_topology_epoch,
    std::uintptr_t transport_backend_context,
    std::uint64_t generation,
    std::uint32_t protocol_stage,
    std::uint64_t workspace_status_offset,
    std::uint64_t dispatch_error_offset,
    std::uint64_t error_begin,
    std::uint64_t error_count,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_direct_dispatch_publish_counts(
    const std::int32_t* kernel_expert_prefix,
    const std::int32_t* kernel_unaligned,
    std::int32_t* public_expert_prefix,
    std::int32_t* public_unaligned,
    std::uint32_t num_experts,
    std::uint32_t local_experts,
    std::uint32_t world_rank,
    std::uint32_t world_size,
    std::uint32_t expert_alignment,
    std::uint32_t expand_mode,
    void* stream, std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_vf_dispatch_epilogue(
    std::uint8_t* communication_buffer,
    std::uint8_t* workspace,
    std::uint8_t* recv_x,
    std::uint8_t* recv_scale_factors,
    std::int64_t* recv_topk_indices,
    float* recv_topk_weights,
    std::int32_t* prefix_per_rank,
    std::int32_t* prefix_per_expert,
    std::int32_t* unaligned_per_expert,
    std::int32_t* source_metadata,
    std::uint32_t transport_abi_version,
    std::uint32_t transport_struct_size,
    std::uint64_t transport_capabilities,
    std::uintptr_t transport_local_window_base,
    std::uintptr_t transport_channel_table,
    std::uintptr_t transport_peer_address_table,
    std::uint32_t transport_topology_abi_version,
    std::uint32_t transport_topology_struct_size,
    int transport_world_rank,
    int transport_world_size,
    int transport_scale_up_rank,
    int transport_scale_up_size,
    int transport_scale_out_rank,
    int transport_scale_out_size,
    std::uint32_t transport_scale_up_direct,
    std::uint32_t transport_topology_kind,
    std::uint64_t transport_topology_epoch,
    std::uintptr_t transport_backend_context,
    CoreModeFlags mode_flags,
    std::uint64_t generation,
    std::uint64_t timeout_cycles,
    std::uint64_t num_tokens,
    std::uint64_t num_experts,
    std::uint64_t num_topk,
    std::uint64_t expert_alignment,
    std::uint64_t shard_capacity,
    std::uint64_t dispatch_output_capacity,
    std::uint64_t control_offset,
    std::uint64_t dispatch_control_offset,
    std::uint64_t dispatch_control_bytes,
    std::uint64_t dispatch_receive_offset,
    std::uint64_t dispatch_receive_shard_bytes,
    std::uint64_t dispatch_receive_shard_count,
    std::uint64_t dispatch_receive_bytes,
    std::uint64_t workspace_scratch_status_offset,
    std::uint64_t workspace_scratch_local_count_offset,
    std::uint64_t workspace_scratch_rank_counts_offset,
    std::uint64_t workspace_scratch_rank_count,
    std::uint64_t token_stride_bytes,
    std::uint64_t token_hidden_offset,
    std::uint64_t token_hidden_bytes,
    std::uint64_t token_scale_factor_offset,
    std::uint64_t token_scale_factor_bytes,
    std::uint64_t recv_scale_factor_token_stride,
    std::uint64_t recv_scale_factor_pack_stride,
    std::uint64_t token_topk_index_offset,
    std::uint64_t token_topk_weight_offset,
    std::uint64_t token_source_metadata_offset,
    std::uint32_t copy_outputs,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_dispatch_producer(
    const std::uint8_t* x,
    const std::uint8_t* scale_factors,
    const std::int64_t* topk_indices,
    const float* topk_weights,
    std::uint8_t* communication_buffer,
    std::uint8_t* workspace,
    std::int32_t* destination_slots,
    std::uint32_t transport_abi_version,
    std::uint32_t transport_struct_size,
    std::uint64_t transport_capabilities,
    std::uintptr_t transport_local_window_base,
    std::uintptr_t transport_channel_table,
    std::uintptr_t transport_peer_address_table,
    std::uint32_t transport_topology_abi_version,
    std::uint32_t transport_topology_struct_size,
    int transport_world_rank,
    int transport_world_size,
    int transport_scale_up_rank,
    int transport_scale_up_size,
    int transport_scale_out_rank,
    int transport_scale_out_size,
    std::uint32_t transport_scale_up_direct,
    std::uint32_t transport_topology_kind,
    std::uint64_t transport_topology_epoch,
    std::uintptr_t transport_backend_context,
    CoreModeFlags mode_flags,
    std::uint64_t generation,
    std::uint64_t timeout_cycles,
    std::uint64_t num_tokens,
    std::uint64_t num_experts,
    std::uint64_t num_topk,
    std::uint64_t shard_capacity,
    std::uint64_t dispatch_control_offset,
    std::uint64_t dispatch_control_bytes,
    std::uint64_t dispatch_receive_offset,
    std::uint64_t dispatch_receive_shard_bytes,
    std::uint64_t dispatch_receive_shard_count,
    std::uint64_t dispatch_receive_bytes,
    std::uint64_t dispatch_staging_offset,
    std::uint64_t dispatch_staging_shard_bytes,
    std::uint64_t dispatch_staging_shard_count,
    std::uint64_t dispatch_staging_bytes,
    std::uint64_t hybrid_dispatch_ingress_control_offset,
    std::uint64_t hybrid_dispatch_ingress_control_bytes,
    std::uint64_t hybrid_dispatch_ingress_shard_offset,
    std::uint64_t hybrid_dispatch_ingress_shard_bytes,
    std::uint64_t hybrid_dispatch_ingress_shard_count,
    std::uint64_t hybrid_dispatch_ingress_bytes,
    std::uint64_t hybrid_dispatch_ingress_staging_offset,
    std::uint64_t hybrid_dispatch_ingress_staging_shard_bytes,
    std::uint64_t hybrid_dispatch_ingress_staging_shard_count,
    std::uint64_t hybrid_dispatch_ingress_staging_bytes,
    std::uint64_t workspace_scratch_status_offset,
    std::uint64_t workspace_scratch_local_count_offset,
    std::uint64_t workspace_scratch_rank_counts_offset,
    std::uint64_t workspace_scratch_rank_values_offset,
    std::uint64_t workspace_scratch_outbound_ingress_counts_offset,
    std::uint64_t workspace_scratch_outbound_ingress_count,
    std::uint64_t workspace_scratch_rank_indices_offset,
    std::uint64_t workspace_scratch_rank_flags_offset,
    std::uint64_t workspace_scratch_rank_count,
    std::uint64_t token_stride_bytes,
    std::uint64_t token_hidden_offset,
    std::uint64_t token_hidden_bytes,
    std::uint64_t token_scale_factor_offset,
    std::uint64_t token_scale_factor_bytes,
    std::uint64_t scale_factor_token_stride,
    std::uint64_t scale_factor_pack_stride,
    std::uint64_t token_topk_index_offset,
    std::uint64_t token_topk_weight_offset,
    std::uint64_t token_source_metadata_offset,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_hybrid_dispatch_forward(
    std::uint8_t* workspace,
    std::uint32_t transport_abi_version,
    std::uint32_t transport_struct_size,
    std::uint64_t transport_capabilities,
    std::uintptr_t transport_local_window_base,
    std::uintptr_t transport_channel_table,
    std::uintptr_t transport_peer_address_table,
    std::uint32_t transport_topology_abi_version,
    std::uint32_t transport_topology_struct_size,
    int transport_world_rank,
    int transport_world_size,
    int transport_scale_up_rank,
    int transport_scale_up_size,
    int transport_scale_out_rank,
    int transport_scale_out_size,
    std::uint32_t transport_scale_up_direct,
    std::uint32_t transport_topology_kind,
    std::uint64_t transport_topology_epoch,
    std::uintptr_t transport_backend_context,
    std::uint64_t generation,
    std::uint64_t timeout_cycles,
    std::uint64_t num_experts,
    std::uint64_t shard_capacity,
    std::uint64_t ingress_control_offset,
    std::uint64_t ingress_shard_offset,
    std::uint64_t ingress_shard_bytes,
    std::uint64_t forward_control_offset,
    std::uint64_t forward_shard_offset,
    std::uint64_t forward_shard_bytes,
    std::uint64_t workspace_status_offset,
    std::uint64_t token_stride_bytes,
    std::uint64_t token_topk_index_offset,
    std::uint64_t token_source_metadata_offset,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_hybrid_dispatch_prepare_epilogue(
    std::uint8_t* workspace,
    std::uint32_t transport_abi_version,
    std::uint32_t transport_struct_size,
    std::uint64_t transport_capabilities,
    std::uintptr_t transport_local_window_base,
    std::uintptr_t transport_channel_table,
    std::uintptr_t transport_peer_address_table,
    std::uint32_t transport_topology_abi_version,
    std::uint32_t transport_topology_struct_size,
    int transport_world_rank,
    int transport_world_size,
    int transport_scale_up_rank,
    int transport_scale_up_size,
    int transport_scale_out_rank,
    int transport_scale_out_size,
    std::uint32_t transport_scale_up_direct,
    std::uint32_t transport_topology_kind,
    std::uint64_t transport_topology_epoch,
    std::uintptr_t transport_backend_context,
    std::uint64_t generation,
    std::uint64_t timeout_cycles,
    std::uint64_t shard_capacity,
    std::uint64_t dispatch_control_offset,
    std::uint64_t dispatch_receive_offset,
    std::uint64_t dispatch_receive_shard_bytes,
    std::uint64_t forward_control_offset,
    std::uint64_t forward_shard_offset,
    std::uint64_t forward_shard_bytes,
    std::uint64_t workspace_status_offset,
    std::uint64_t token_stride_bytes,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);

extern "C" int deep_ep_ascend_launch_hybrid_dispatch_record_routes(
    std::uint8_t* workspace,
    HybridRouteRecord* route_records,
    std::uintptr_t transport_local_window_base,
    std::uintptr_t transport_backend_context,
    int transport_world_rank,
    int transport_world_size,
    int transport_scale_up_size,
    std::uint64_t topology_epoch,
    std::uint64_t generation,
    std::uint64_t num_experts,
    std::uint64_t shard_capacity,
    std::uint64_t route_record_capacity,
    std::uint64_t dispatch_control_offset,
    std::uint64_t dispatch_receive_offset,
    std::uint64_t dispatch_receive_shard_bytes,
    std::uint64_t workspace_status_offset,
    std::uint64_t token_stride_bytes,
    std::uint64_t token_topk_index_offset,
    std::uint64_t token_source_metadata_offset,
    void* stream, CoreLaunchShape launch,
    std::uint32_t vf_num_threads);
